### ISSUE TITLE
FTBLib breaks MineTweaker Script Sending

### ISSUE THREAD

**Issue by Sir-Will** [FTBTeam/FTB-Library#20]
hey,

if I have FTBLib-1.7.10-1.0.17.6 enabled on the server the scripts from minetweaker no longer get send to the clients except I run /mt reload but after a reconnect the recipes are gone again.

So something in this mod prevents minetweaker of sending the scripts to the client when he joins the server.

**Comment by LatvianModder** [comment]
Not really my fault, but I will leave it here anyway until I can confirm that this can be fixed in FTBTweaks :P

**Comment by Sir-Will** [comment]
I only had FTBLib without FTBTweaks or any other FTB mod enabled.

**Comment by LatvianModder** [comment]
Ah. Hm. Without FTBTweaks, it shouldn't override MT at all. Like. I dont even have any scripts related code in FTBLib

**Comment by Sir-Will** [comment]
Hm, that's weird. You can test it yourself if you want.
#17 does seem to have the same issue.

**Comment by darkcamo12** [comment]
From what I have noticed the server is sending the correct information which the client is receiving but then all of a sudden the client is then loading it's own modpacks folder most times it loads the default modpack

**Comment by LatvianModder** [comment]
This could be fixed, if FTBTweaks sent script packet after reloading it. Buuuuut.. 1.7.10 is pretty much closed and neither me nor Jared want to fix anything :P I will see if I can edit it myself maybe

**Comment by jaredlll08** [comment]
well wait, he said that is happened without FTB Tweaks...

**Comment by LatvianModder** [comment]
Yeah but that's impossible, since neither FTBLib nor FTBUtilities do anything with scripts. Again. 1.7.10 is closed, especially with Infinity 1.10 right around the corner

**Comment by jaredlll08** [comment]
Yea I know, someone just sent me a tweet asking to fix this...

**Comment by KasperFranz** [comment]
This seems to be the same problem on 1.10.

when you join it doesn't load your config but after a /mt reload it works again. (or after a ftbl:reload) and breaks again after /ftb reload_client

**Comment by jaredlll08** [comment]
@KasperFranz do you have FTBTweaks installed?

**Comment by KasperFranz** [comment]
Yes

På 17. mar. 2017 5.51 PM, Jared <notifications@github.com> skrev:

@KasperFranz do you have FTBTweaks installed?

**Comment by KasperFranz** [comment]
any update on this :)?
