### ISSUE TITLE
The game crashed whilst keypressed event handler Error: java.lang.NoClassDefFoundError: com/feed_the_beast/mods/ftbguilibrary/utils/Key Exit Code: -1

### ISSUE THREAD

**Issue by XLunaThisOfficial** [FTBTeam/FTB-Library#27]
[crash-2021-05-05_15.14.51-client.txt](https://github.com/FTBTeam/FTB-Library/files/6426838/crash-2021-05-05_15.14.51-client.txt)
why well it crashes it has a problem the time im making quest for my upcoming modpack when i create a quest item i cant choose any items totally its nothing and the scroll is broken its texture is inventory buttons then it crashed

**Comment by JuicyCosmos** [comment]
How did you fix it? I'm having the exact same problem with all the recent versions of ftb lib and quest mod. Previously the bug was able to solve itself but now does not go away anymore.
