### ISSUE TITLE
Name change in FTB- Gui Library causing issues 

### ISSUE THREAD

**Issue by Samical** [FTBTeam/FTB-Library#28]
I am trying to use the latest versions of the FTB mods and I am getting a notification that FTB Gui library  is not installed. 

The latest version of FTB- Gui-Library had its name change to just FTB-Library 

This is causing FTB chunks to throw the error , when downgrading the FTB GUi Library to the last version that had GUI in the file name other mods say that FTB Library  (no gui) is not installed.

**Comment by MaxNeedsSnacks** [comment]
This should've just resolved itself by now if you've updated to our latest releases ^^
