### ISSUE TITLE
jei says its missing this even though its installed

### ISSUE THREAD

**Issue by Chilly1994** [FTBTeam/FTB-Library#30]
![image](https://user-images.githubusercontent.com/85046619/120091283-3c750f80-c0cf-11eb-959f-62b73387aa1c.png)
![image](https://user-images.githubusercontent.com/85046619/120091297-5b73a180-c0cf-11eb-8672-38fc9de9f48f.png)

no idea how to fix it after I googled around for about 3 hours. if anyone know what I'm doing wrong any assistance would be helpful. Thank you all.

**Comment by Kayno0o** [comment]
I had the same issue, just use the latest version and it will work

**Comment by MichaelHillcox** [comment]
Please us the latest version of the mod. (We changed mod name and pushed an update to JEI to go with it) (it's now called FTB Library *again*)
