### ISSUE TITLE
[bug] Windows Defender detects trojan in update.

### ISSUE THREAD

**Issue by cucumpear** [FTBTeam/FTB-Library#35]
Today's update of FTB Library (ftb-library-forge-1605.3.2-build.64) gets flagged as a trojan by Windows Defender. Installing other mods (via curseforge app) or previous versions doesn't show the same issue.
![Screenshot 2021-08-20 143048](https://user-images.githubusercontent.com/21053609/130234842-bc9056f5-cfba-401c-beff-a293515a530b.png)

**Comment by MaxNeedsSnacks** [comment]
This is unfortunately a known false-positive issue and seems to be happening to quite a few mods for no discernible reason. (CurseForge actually published an announcement about this in their Discord)

Until this is fixed (probably through an AV definition update), I'd recommend you either stay on the old version or manually trust the new one (FWIW *I* didn't include any viruses in it at least 😉)
