### ISSUE TITLE
FakePlayers Issue

### ISSUE THREAD

**Issue by thefinaldegree** [FTBTeam/FTB-Library#69]
Issue with FakePlayers - when the fake player joins, the "You haven't joined or created a team yet! " message (from `onPlayerLoggedIn(PlayerEvent.PlayerLoggedInEvent e)` in [FTBLibEventHandler.java](https://github.com/LatvianModder/FTBLib/blob/master/src/main/java/com/feed_the_beast/ftbl/FTBLibEventHandler.java)) is sent to all players on the server.

The FakePlayer in question is from this mod: [iExtras](https://minecraft.curseforge.com/projects/iextras)
I believe it's specifically when the player is initialised at `initializeFakePlayer()` in [TileEntityIExecutor.java](https://github.com/Zairus/iExtras/blob/master/src/main/java/zairus/iextras/tileentity/TileEntityIExecutor.java)

**Comment by LatvianModder** [comment]
This should fix it https://github.com/LatvianModder/FTBLib/blob/master/src/main/java/com/feed_the_beast/ftbl/api_impl/ForgePlayer.java#L312
